[tool.ruff]
target-version = "py313"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D1",     # Undocumented items
    "COM812", # Conflicts with formatter.
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.typos.default.extend-identifiers]
hass = "hass"
